package com.sentinel.bridge.feature.pipeline.handlers

import com.sentinel.bridge.core.common.logging.SentinelLogger
import com.sentinel.bridge.core.domain.interfaces.AIProvider
import com.sentinel.bridge.core.domain.model.ErrorCategory
import com.sentinel.bridge.core.domain.model.InferenceConfig
import com.sentinel.bridge.core.domain.model.PipelineStage
import com.sentinel.bridge.core.domain.model.SentinelError
import com.sentinel.bridge.feature.pipeline.BaseCommandHandler
import com.sentinel.bridge.feature.pipeline.CommandResult
import com.sentinel.bridge.feature.pipeline.PipelineSessionStore
import com.sentinel.bridge.feature.pipeline.commands.PipelineCommand
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.time.Instant
import javax.inject.Inject

/**
 * Runs local LLM inference via [AIProvider] (backed by LlamaCppProvider).
 *
 * Reads the prompt the build-prompt stage rendered, ensures the model is loaded,
 * runs inference, and stores the raw output on the session for the parse stage.
 *
 * Uses `maxRetries = 1` to allow one automatic retry on transient inference
 * failures such as an OOM during token generation.
 */
open class RunInferenceHandler @Inject constructor(
    private val logger: SentinelLogger,
    private val aiProvider: AIProvider,
    private val sessionStore: PipelineSessionStore
) : BaseCommandHandler<PipelineCommand.RunInference>(maxRetries = 1) {

    override val stage: PipelineStage = PipelineStage.INFERENCE

    /**
     * Runs inference over the session's rendered prompt.
     *
     * @throws com.sentinel.bridge.feature.pipeline.MissingSessionStateException if no
     *         prompt is present.
     * @throws IllegalStateException if the model could not be loaded, or if the model
     *         returned nothing — an empty completion cannot be parsed and is reported
     *         here where the cause is still visible.
     */
    override suspend fun doExecute(command: PipelineCommand.RunInference): CommandResult {
        val prompt = sessionStore.requirePrompt(command.sessionId)

        logger.logInfo(
            command.sessionId,
            stage.name,
            "Starting LLM inference (prompt=${prompt.length} chars)"
        )

        if (!aiProvider.isAvailable) {
            aiProvider.loadModel().getOrElse { cause ->
                throw IllegalStateException("Failed to load the AI model: ${cause.message}", cause)
            }
        }

        val settings = sessionStore.get(command.sessionId)?.inference
        val config = InferenceConfig(
            temperature = settings?.temperature ?: DEFAULT_TEMPERATURE,
            maxTokens = settings?.maxTokens ?: DEFAULT_MAX_TOKENS,
            topP = settings?.topP ?: DEFAULT_TOP_P,
            topK = settings?.topK ?: DEFAULT_TOP_K,
            repeatPenalty = settings?.repeatPenalty ?: DEFAULT_REPEAT_PENALTY,
            contextSize = DEFAULT_CONTEXT_SIZE,
            threads = DEFAULT_THREADS
        )

        val startedAt = System.currentTimeMillis()
        val output = inferWithDeadline(command.sessionId, prompt, config)
        val elapsedMs = System.currentTimeMillis() - startedAt

        check(output.isNotBlank()) {
            "The model returned no output after ${elapsedMs / 1000}s. It may have been " +
                "cancelled before producing anything."
        }

        sessionStore.update(command.sessionId) { it.copy(rawResponse = output) }

        logger.logInfo(
            command.sessionId,
            stage.name,
            "Inference completed in ${elapsedMs}ms (output=${output.length} chars)"
        )

        return CommandResult.Success(command.sessionId)
    }

    /**
     * Runs inference under a deadline, returning whatever was generated by the time it
     * expires.
     *
     * [AIProvider.infer] blocks in a JNI call, so cancelling the coroutine cannot
     * interrupt it — the native loop only stops when its cancellation flag is set. A
     * watchdog therefore sets that flag when the deadline passes; the native loop checks
     * it once per token and returns the partial output.
     *
     * Without this a run that fails to terminate leaves the caller waiting indefinitely,
     * which is what a missing chat template used to produce.
     */
    private suspend fun inferWithDeadline(
        sessionId: String,
        prompt: String,
        config: InferenceConfig
    ): String = coroutineScope {
        val watchdog = launch {
            delay(INFERENCE_DEADLINE_MS)
            logger.logError(
                sessionId,
                stage.name,
                "Inference exceeded ${INFERENCE_DEADLINE_MS / 1000}s, cancelling"
            )
            aiProvider.cancelInference()
        }

        try {
            aiProvider.infer(prompt, config)
        } finally {
            watchdog.cancel()
        }
    }

    override fun buildError(command: PipelineCommand.RunInference, exception: Exception): SentinelError {
        return SentinelError(
            code = "ERR_INFERENCE",
            category = ErrorCategory.INFERENCE,
            message = exception.message ?: "LLM inference failed",
            stage = stage,
            retryable = true,
            timestamp = Instant.now(),
            sessionId = command.sessionId
        )
    }

    private companion object {
        // Fallbacks only — the prompt template supplies these in practice.
        const val DEFAULT_TEMPERATURE = 0.3f
        const val DEFAULT_MAX_TOKENS = 1024
        const val DEFAULT_TOP_P = 0.9f
        const val DEFAULT_TOP_K = 40
        const val DEFAULT_REPEAT_PENALTY = 1.1f
        const val DEFAULT_CONTEXT_SIZE = 4096
        const val DEFAULT_THREADS = 4

        /**
         * Longest a single generation may run before the native loop is cancelled.
         *
         * Sized for a 4B model on phone-class CPU: a few tokens per second means even a
         * well-behaved run takes minutes, so this is generous, but it bounds the failure
         * case rather than letting a run hang until the user gives up.
         */
        const val INFERENCE_DEADLINE_MS = 5 * 60 * 1000L
    }
}
